"""
Django settings for romhoard project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
# Priority: 1) DJANGO_SECRET_KEY env var, 2) persistent file, 3) auto-generate
def _get_secret_key() -> str:
    """Get or generate a persistent secret key."""
    import secrets

    # 1. Check environment variable
    if env_key := os.environ.get("DJANGO_SECRET_KEY"):
        return env_key

    # 2. Check for persistent secret file in data directory
    data_dir = Path(os.environ.get("DATA_DIR", BASE_DIR / "data"))
    secret_file = data_dir / ".secret_key"

    if secret_file.exists():
        return secret_file.read_text().strip()

    # 3. Generate new secret and persist it
    new_secret = secrets.token_urlsafe(50)
    try:
        data_dir.mkdir(parents=True, exist_ok=True)
        secret_file.write_text(new_secret)
        secret_file.chmod(0o600)  # Owner read/write only
    except OSError:
        # Can't persist (read-only filesystem?) - use generated key for this run
        import warnings

        warnings.warn(
            f"Could not persist secret key to {secret_file}. Key will be regenerated on restart.",
            UserWarning,
            stacklevel=2,
        )
    return new_secret


SECRET_KEY = _get_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=false in production
DEBUG = os.environ.get("DEBUG", "true").lower() in ("true", "1", "yes")

# Use bundled assets (Docker) vs CDN (development)
# Set USE_BUNDLED_ASSETS=true in Docker to serve local JS/CSS/fonts instead of CDN
USE_BUNDLED_ASSETS = os.environ.get("USE_BUNDLED_ASSETS", "false").lower() in ("true", "1", "yes")

# ALLOWED_HOSTS can be set via environment variable (comma-separated)
# Example: ALLOWED_HOSTS=example.com,www.example.com
# Default: accept any host (single-user self-hosted app)
_env_hosts = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _env_hosts.split(",") if h.strip()] or ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "procrastinate.contrib.django",
    "library",
    "romcollections",
    "devices",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "romhoard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "romhoard.context_processors.bundled_assets",
            ],
        },
    },
]

WSGI_APPLICATION = "romhoard.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "romhoard"),
        "USER": os.environ.get("POSTGRES_USER", "dev_admin"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "dev_admin"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for serving static files in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Logging configuration
# Supports both console and file output via LOG_FILE environment variable
LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
LOG_FILE = os.environ.get("LOG_FILE")

# Build handlers list - always include console, add file if LOG_FILE is set
handlers = ["console"]
if LOG_FILE:
    handlers.append("file")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": handlers,
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",  # Keep Django logs quiet even in debug mode
            "propagate": False,
        },
        # Library app loggers - inherit from root but can be configured separately
        "library": {
            "handlers": handlers,
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "library.metadata": {
            "handlers": handlers,
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "romcollections": {
            "handlers": handlers,
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "devices": {
            "handlers": handlers,
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "procrastinate": {
            "handlers": handlers,
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Add file handler if LOG_FILE is configured
if LOG_FILE:
    LOGGING["handlers"]["file"] = {
        "class": "logging.FileHandler",
        "filename": LOG_FILE,
        "formatter": "standard",
    }


# ROM Library Configuration
# Set ROM_LIBRARY_ROOT to enable relative path storage (improves portability)
# When set, all ROM paths are stored relative to this directory
# Example: ROM_LIBRARY_ROOT = "/home/user/roms"
ROM_LIBRARY_ROOT = os.environ.get("ROM_LIBRARY_ROOT", "")

# Image Storage Configuration
# Set IMAGE_STORAGE_PATH for a dedicated image storage directory
# When not set, falls back to ROM_LIBRARY_ROOT/images or data/images
# Example: IMAGE_STORAGE_PATH = "/images"
IMAGE_STORAGE_PATH = os.environ.get("IMAGE_STORAGE_PATH", "")

# Collection Import Configuration
# Maximum file size for collection imports (1GB)
# This affects both file uploads and URL-based imports
COLLECTION_IMPORT_MAX_SIZE = 1 * 1024 * 1024 * 1024  # 1GB in bytes

# Maximum uncompressed size for ZIP validation (2GB)
# Prevents zip bomb attacks where a small ZIP expands to massive size
COLLECTION_IMPORT_MAX_UNCOMPRESSED_SIZE = 2 * 1024 * 1024 * 1024  # 2GB in bytes

# Django upload settings - allow large file uploads
# DATA_UPLOAD_MAX_MEMORY_SIZE must be large enough to accept the request
DATA_UPLOAD_MAX_MEMORY_SIZE = 1 * 1024 * 1024 * 1024  # 1GB

