# Generated by Django 6.0 on 2026-01-30 01:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(1000)],
                    ),
                ),
                ("creator", models.CharField(blank=True, max_length=255)),
                ("is_public", models.BooleanField(default=True)),
                ("is_community", models.BooleanField(default=False)),
                ("is_favorites", models.BooleanField(db_index=True, default=False)),
                ("tags", models.JSONField(default=list)),
                (
                    "cover_image_path",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("has_cover", models.BooleanField(db_index=True, default=False)),
                (
                    "cover_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("uploaded", "Uploaded"),
                            ("generated", "Generated"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "cover_generation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cover", "Game Covers"),
                            ("screenshot", "Screenshots"),
                            ("mix", "Mix Images"),
                        ],
                        default="cover",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_favorites", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_favorites", True)),
                        fields=("is_favorites",),
                        name="unique_favorites_collection",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("entries_total", models.IntegerField(default=0)),
                ("entries_processed", models.IntegerField(default=0)),
                ("images_total", models.IntegerField(default=0)),
                ("images_processed", models.IntegerField(default=0)),
                (
                    "current_game",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("file_path", models.CharField(blank=True, max_length=1000)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                ("games_exported", models.IntegerField(default=0)),
                ("images_exported", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="romcollections.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=255)),
                ("system_slug", models.CharField(max_length=50)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(1000)],
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="romcollections.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("collection", "game_name", "system_slug")},
            },
        ),
        migrations.CreateModel(
            name="CoverJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload Processing"),
                            ("generate", "Auto-Generate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("cover", "Game Covers"),
                            ("screenshot", "Screenshots"),
                            ("mix", "Mix Images"),
                        ],
                        default="cover",
                        max_length=20,
                    ),
                ),
                (
                    "upload_path",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_jobs",
                        to="romcollections.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["collection", "status"],
                        name="romcollecti_collect_status_idx",
                    )
                ],
            },
        ),
    ]
