# Generated by Django 6.0 on 2026-01-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("romcollections", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["is_public", "-created_at"],
                name="romcollecti_is_publ_dcd6a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionentry",
            index=models.Index(
                fields=["system_slug"], name="romcollecti_system__a62726_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionentry",
            index=models.Index(
                fields=["collection", "system_slug"],
                name="romcollecti_collect_60eef1_idx",
            ),
        ),
    ]
