# Generated by Django 6.0 on 2026-02-07 02:54

import re
from django.db import migrations


def slugify_creators(apps, schema_editor):
    """Convert existing creator values to valid slugs."""
    Collection = apps.get_model("romcollections", "Collection")

    for collection in Collection.objects.all():
        original = collection.creator
        # Convert to lowercase and replace spaces with hyphens
        slugified = original.lower().replace(" ", "-")
        # Remove any non-slug characters (keep only a-z, 0-9, hyphens, underscores)
        slugified = re.sub(r"[^a-z0-9_-]", "", slugified)
        # Replace multiple hyphens with single
        slugified = re.sub(r"-+", "-", slugified)
        # Strip leading/trailing hyphens
        slugified = slugified.strip("-")

        if slugified != original:
            collection.creator = slugified
            collection.save(update_fields=["creator"])
            print(f"  Updated: '{original}' -> '{slugified}'")


def reverse_slugify(apps, schema_editor):
    """No-op reverse - we don't want to un-slugify."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("romcollections", "0004_creator_slug_unique_together"),
    ]

    operations = [
        migrations.RunPython(slugify_creators, reverse_slugify),
    ]
