# Generated by Django 6.0 on 2026-02-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("romcollections", "0005_slugify_creators"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="source_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
