# Generated by Django 6.0 on 2026-01-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "root_path",
                    models.CharField(
                        default="Roms/",
                        help_text="Root path in ZIP (e.g., 'Roms/', '/Roms/', 'ROMS/')",
                        max_length=255,
                    ),
                ),
                (
                    "system_paths",
                    models.JSONField(
                        default=dict,
                        help_text="Per-system folder config: {system_slug: {folder: str, game_folders?: bool}}",
                    ),
                ),
                (
                    "has_wifi",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this device has WiFi capability for FTP/SFTP transfers",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("ftp", "FTP"),
                            ("ftps", "FTPS (TLS)"),
                            ("sftp", "SFTP (SSH)"),
                        ],
                        default="",
                        help_text="Protocol for transferring ROMs to device",
                        max_length=10,
                    ),
                ),
                (
                    "transfer_host",
                    models.CharField(
                        blank=True,
                        help_text="FTP/SFTP server hostname or IP",
                        max_length=255,
                    ),
                ),
                (
                    "transfer_port",
                    models.IntegerField(
                        blank=True,
                        help_text="Port (default: 21 for FTP/FTPS, 22 for SFTP)",
                        null=True,
                    ),
                ),
                (
                    "transfer_user",
                    models.CharField(blank=True, help_text="Username", max_length=100),
                ),
                (
                    "_transfer_password",
                    models.CharField(
                        blank=True,
                        db_column="transfer_password",
                        help_text="Encrypted password",
                        max_length=255,
                    ),
                ),
                (
                    "transfer_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Use anonymous FTP login (no credentials)",
                    ),
                ),
                (
                    "transfer_path_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Absolute path to storage mount point on device (e.g., '/mnt/SDCARD')",
                        max_length=255,
                    ),
                ),
                (
                    "include_images",
                    models.BooleanField(
                        default=False,
                        help_text="Include images when sending/downloading games to this device",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[("cover", "Box Art"), ("screenshot", "Screenshot")],
                        default="cover",
                        help_text="Default image type to include",
                        max_length=20,
                    ),
                ),
                (
                    "applied_preset",
                    models.CharField(
                        blank=True,
                        help_text="Slug of last applied preset (informational only)",
                        max_length=50,
                    ),
                ),
                (
                    "image_path_template",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path pattern for images. Placeholders: {root_path}, {system}, {romname}, {romname_ext}",
                        max_length=255,
                    ),
                ),
                (
                    "image_max_width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum image width in pixels (resizes maintaining aspect ratio)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DevicePreset",
            fields=[
                (
                    "slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Search tags like ['muos', 'anbernic']"
                    ),
                ),
                (
                    "is_builtin",
                    models.BooleanField(
                        default=False, help_text="True for repo-shipped presets"
                    ),
                ),
                (
                    "folders_config",
                    models.JSONField(
                        blank=True,
                        help_text="Folder settings: {root_path, system_paths}",
                        null=True,
                    ),
                ),
                (
                    "images_config",
                    models.JSONField(
                        blank=True,
                        help_text="Image settings: {path_template, max_width, image_type}",
                        null=True,
                    ),
                ),
                (
                    "transfer_config",
                    models.JSONField(
                        blank=True,
                        help_text="Transfer settings: {protocol, port, user, password, path_prefix, anonymous}",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
